
name = "leamsp-api"
main = "src/index.ts"
compatibility_date = "2025-07-31"
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
# Use the default worker build process
command = ""

# Environment variables for all environments
[vars]
ENVIRONMENT = "development"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "leamsp-db"
database_id = "03424b8b-54a4-4c29-8e82-9e50330613f2"
migrations_dir = "migrations"

# Production environment
[env.production]
name = "leamsp-api"
workers_dev = true

[env.production.vars]
ENVIRONMENT = "production"

# Development environment
[env.development]
name = "leamsp-api-dev"
workers_dev = true

[env.development.vars]
ENVIRONMENT = "development"
